freeze_files:
    - meta.yml
    - backstop_data/bitmaps_reference/
    - backstop_data/casper_scripts/
    - package.json
    - .drone.yml
    - .report.json
    - public/fonts.css
    - public/basic.css
    - public/normalize.css
    - public/fonts/
    - public/index.html
    - public/long-sidebar.html
    - public/nest-other-layout.html
    - public/content-with-background.html
    - backstop.json
    - package.json
    - README.md
report_files:
    - xunit.xml
report_target: .report.json
